name: Docker CI/CD 自动部署

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 构建 Docker 镜像
      - name: Build Docker Image
        run: docker build -t vue-app .

      # 推送到服务器（正确写法！）
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            # 删除旧容器
            docker stop vue-app || true
            docker rm vue-app || true

            # 删除旧镜像
            docker rmi vue-app || true

            # 拉新代码并构建
            cd /root || mkdir /root
            git clone https://github.com/peixiaomin/practice-web.git temp || cd temp && git pull
            docker build -t vue-app temp/.

            # 启动
            docker run -d \
              --name vue-app \
              --restart always \
              -p 80:80 \
              vue-app
