name: Docker 自动部署
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 部署到云服务器
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            # 1. 进入工作目录
            mkdir -p /data/practice-web
            cd /data/practice-web

            # 2. 拉代码（如果没有就克隆，有就更新）
            if [ ! -d ".git" ]; then
              git clone https://github.com/peixiaomin/practice-web.git .
            else
              git pull
            fi

            # 3. 重启容器
            docker stop vue-app || true
            docker rm vue-app || true
            docker rmi vue-app || true

            # 4. 构建镜像
            docker build -t vue-app .

            # 5. 启动容器
            docker run -d \
              --name vue-app \
              --restart always \
              -p 80:80 \
              vue-app
